#NAME: Joel George
#EMAIL: joelgeorge03@gmail.com
#ID: 004786402

CC = gcc
CFLAGS = -g -Wall -Wextra -lpthread

default: lab1a.c
        $(CC) $(CFLAGS) lab2_add.c -o lab2-add
	$(CC) $(CFLAGS) lab2_list.c SortedList.c lab2-list

test:
	@-./lab2_add --threads=1  --iterations=10	           >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=100	   >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=1000	   >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=10000	   >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=20000	   >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=100000         >> lab2_add.csv

	@-./lab2_add --threads=2  --iterations=1             >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=10            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=20            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=40            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=80            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=100           >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=1000          >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=20000         >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=100000         >> lab2_add.csv

	@-./lab2_add --threads=4  --iterations=1             >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=10            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=20            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=40            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=100           >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=1000          >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=20000         >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=100000         >> lab2_add.csv

	@-./lab2_add --threads=8  --iterations=1             >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=10            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=20            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=40            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=80            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=100           >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=1000          >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=20000         >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=100000         >> lab2_add.csv

	@-./lab2_add --threads=12 --iterations=1             >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=10            >> lab2_add.csv
	@-./lab2_add --threads=12  --iterations=20            >> lab2_add.csv
	@-./lab2_add --threads=12  --iterations=40            >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=100           >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=1000          >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=20000         >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=100000         >> lab2_add.csv

	@-./lab2_add --threads=2  --iterations=1 --yield             >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=10 --yield            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=20 --yield            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=40 --yield            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=80 --yield            >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=100 --yield           >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=1000 --yield          >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=20000 --yield         >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=100000 --yield         >> lab2_add.csv

	@-./lab2_add --threads=4  --iterations=1 --yield             >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=10 --yield            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=20 --yield            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=40 --yield            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=80 --yield            >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=100 --yield           >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=1000 --yield          >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=20000 --yield         >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=100000 --yield         >> lab2_add.csv

	@-./lab2_add --threads=8  --iterations=1 --yield             >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=10 --yield            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=20 --yield            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=40 --yield            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=80 --yield            >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=100 --yield           >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=1000 --yield          >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=20000 --yield         >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=100000 --yield         >> lab2_add.csv

	@-./lab2_add --threads=12  --iterations=1 --yield             >> lab2_add.csv
	@-./lab2_add --threads=12  --iterations=10 --yield            >> lab2_add.csv
	@-./lab2_add --threads=12  --iterations=20 --yield            >> lab2_add.csv
	@-./lab2_add --threads=12  --iterations=40 --yield            >> lab2_add.csv
	@-./lab2_add --threads=12  --iterations=80 --yield            >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=100 --yield           >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=1000 --yield          >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=20000 --yield         >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=100000 --yield         >> lab2_add.csv


	@-./lab2_add --threads=1  --iterations=1000                   >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=10000 --yield --sync=m >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=1000 --yield --sync=s >> lab2_add.csv
	@-./lab2_add --threads=1 --iterations=10000 --yield --sync=c >> lab2_add.csv
	@-./lab2_add --threads=2 --iterations=10000 --yield --sync=c >> lab2_add.csv
	@-./lab2_add --threads=4 --iterations=10000 --yield --sync=c >> lab2_add.csv
	@-./lab2_add --threads=8 --iterations=10000 --yield --sync=c >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=10000 --yield --sync=c >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=10000 --yield --sync=c >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=10000 --yield --sync=c >> lab2_add.csv

	@-./lab2_add --threads=1  --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=10000 --sync=m >> lab2_add.csv
	@-./lab2_add --threads=1  --iterations=1000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=1000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=1000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=1000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=1000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=1000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=1000  --sync=s >> lab2_add.csv

	@-./lab2_add --threads=1 --iterations=10000  --sync=c >> lab2_add.csv
	@-./lab2_add --threads=2 --iterations=10000 --sync=c >> lab2_add.csv
	@-./lab2_add --threads=4 --iterations=10000 --sync=c >> lab2_add.csv
	@-./lab2_add --threads=8 --iterations=10000 --sync=c >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=10000 --sync=c >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=10000 --sync=c >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=10000 --sync=c >> lab2_add.csv

	@-./lab2_add --threads=1  --iterations=10000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=2  --iterations=10000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=4  --iterations=10000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=8  --iterations=10000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=12 --iterations=10000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=16 --iterations=10000  --sync=s >> lab2_add.csv
	@-./lab2_add --threads=24 --iterations=10000  --sync=s >> lab2_add.csv



	@-./lab2_list --threads=1  --iterations=10	      >> lab2_list.csv
	@-./lab2_list --threads=1  --iterations=100	      >> lab2_list.csv
	@-./lab2_list --threads=1  --iterations=1000	      >> lab2_list.csv
	@-./lab2_list --threads=1  --iterations=10000	      >> lab2_list.csv
	@-./lab2_list --threads=1  --iterations=20000	      >> lab2_list.csv

	@-./lab2_list --threads=2  --iterations=1              >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=10             >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=100            >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=1000           >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1              >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=10             >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=100            >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1000           >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1              >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=10             >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=100            >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1000           >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1              >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=10             >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=100            >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1000           >> lab2_list.csv

	@-./lab2_list --threads=2  --iterations=1   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=2   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=4   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=8   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=12   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=16  --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=32  --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=2   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=4   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=8   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=8   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=16  --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=2   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=4   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=8   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=8   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=16  --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=2   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=4   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=8   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=12  --iterations=12   --yield=i  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=16  --yield=i  >> lab2_list.csv

	@-./lab2_list --threads=2  --iterations=1   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=2   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=4   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=8   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=16  --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=32  --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=2   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=4   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=8   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=16  --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=2   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=4   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=8   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=16  --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=2   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=4   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=8   --yield=d  >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=16  --yield=d  >> lab2_list.csv

	@-./lab2_list --threads=2  --iterations=1   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=2   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=4   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=8   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=16  --yield=il >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=32  --yield=il >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=2   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=4   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=8   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=16  --yield=il >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=2   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=4   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=8   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=16  --yield=il >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=2   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=4   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=8   --yield=il >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=16  --yield=il >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=1   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=2   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=4   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=8   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=16  --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=32  --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=2   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=4   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=8   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=16  --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=2   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=4   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=8   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=16  --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=2   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=4   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=8   --yield=dl >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=16  --yield=dl >> lab2_list.csv

	@-./lab2_list --threads=12 --iterations=32 --yield=i  --sync=m >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=d  --sync=m >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=il --sync=m >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=dl --sync=m >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=i  --sync=s >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=d  --sync=s >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=il --sync=s >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=32 --yield=dl --sync=s >> lab2_list.csv

	@-./lab2_list --threads=1  --iterations=1000          >> lab2_list.csv
	@-./lab2_list --threads=1  --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=16 --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=24 --iterations=1000 --sync=m >> lab2_list.csv
	@-./lab2_list --threads=1  --iterations=1000 --sync=s >> lab2_list.csv
	@-./lab2_list --threads=2  --iterations=1000 --sync=s >> lab2_list.csv
	@-./lab2_list --threads=4  --iterations=1000 --sync=s >> lab2_list.csv
	@-./lab2_list --threads=8  --iterations=1000 --sync=s >> lab2_list.csv
	@-./lab2_list --threads=12 --iterations=1000 --sync=s >> lab2_list.csv
	@-./lab2_list --threads=16 --iterations=1000 --sync=s >> lab2_list.csv
	@-./lab2_list --threads=24 --iterations=1000 --sync=s >> lab2_list.csv

graphs:
	@-gnuplot lab2_add.gp
	@-gnuplot lab2_list.gp

clean:
        rm -f *.o *.so *.tgz lab2_add lab1a-004786402.tar.gz

submission_files = README Makefile lab2_add.c lab2_list.c lab2_add.gp lab2_list.gp lab2_add.csv lab2_list.csv lab2_add-1.png lab2_add-2.png lab2_add-3.png lab2_add-4.png lab2_add-5.png lab2_list-1.png lab2_list-2.png lab2_list-3.png lab2_list-4.png SortedList.c SortedList.h

dist:
        tar -czf lab2a-004786402.tar.gz $(submission_files)

.PHONY: default clean dist
